In [1]:
from torch import tensor
import torch

In [3]:
i = tensor(7)
assert(i == 7)
assert(i.ndim == 0)
assert(i.shape == torch.Size([]))

In [7]:
a = tensor([1])
assert(a[0] == 1)
assert(a.ndim == 1)
assert(a.shape == torch.Size([1]))

b = tensor([2])
assert(b[0] == 2)
assert(b.ndim == 1)
assert(b.shape == torch.Size([1]))

c = a + b
assert(c[0] == 3)
assert(c.ndim == 1)
assert(c.shape == torch.Size([1]))

In [8]:
x = tensor([1, 2, 3])
assert(x.ndim == 1)
assert(x.shape == torch.Size([3]))

y = tensor([4, 5, 6])
assert(y.ndim == 1)
assert(y.shape == torch.Size([3]))

z = x + y
assert(z.ndim == 1)
assert(z.shape == torch.Size([3]))

In [11]:
# Row vector matrix
A = tensor([[1, 2, 3]])
assert(A.ndim == 2) 
assert(A.shape == torch.Size([1, 3]))

# Column vector matrix
B = A.T
assert(B.ndim == 2)
assert(B.shape == torch.Size([3, 1]))

# Dot product
C = A @ B
assert(C.item() == 14)
assert(C.ndim == 2)
assert(C.shape == torch.Size([1, 1]))

In [16]:
torch.manual_seed(0)
R = torch.rand(size=(3, 3))

# tensor([[0.4963, 0.7682, 0.0885],
#         [0.1320, 0.3074, 0.6341],
#         [0.4901, 0.8964, 0.4556]])

In [17]:
D = torch.diag(input=torch.tensor([1, 2, 3]))

# tensor([[1, 0, 0],
#         [0, 2, 0],
#         [0, 0, 3]])

In [18]:
E = torch.eye(n=3)

# tensor([[1., 0., 0.],
#         [0., 1., 0.],
#         [0., 0., 1.]])

In [19]:
Z = torch.zeros(size=(3, 3))

# tensor([[0., 0., 0.],
#         [0., 0., 0.],
#         [0., 0., 0.]])

In [21]:
r = torch.arange(start=0, end=10, step=1)

# tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
x = tensor([[1., 2., 3., 4., 5.],
            [6., 7., 8., 9., 10.]])

assert(x.ndim == 2)
assert(x.shape == (2, 5))

assert(x[0][0] == 1.0)
assert(x[0][1] == 2.0)
assert(x[1][0] == 6.0)

assert(x[0, 0] == 1.0)
assert(x[0, 1] == 2.0)
assert(x[1, 0] == 6.0)

# x[:, 0] is like x[*, 0], which means [0, 0], [1, 0], ..., [n, 0]
assert(torch.allclose(x[:, 0], tensor([1., 6.])))

# x[0, :] is like x[0, *], which means [0, 0], [0, 1], ..., [0, n]
assert(torch.allclose(x[0, :], tensor([1., 2., 3., 4., 5.])))